# Generated by Django 3.0.4 on 2020-03-18 11:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='medical_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('L_CORE', models.IntegerField(max_length=4)),
                ('L_SURF', models.IntegerField(max_length=4)),
                ('L_O2', models.IntegerField(max_length=4)),
                ('L_BP', models.IntegerField(max_length=4)),
                ('SURF_STBL', models.IntegerField(max_length=4)),
                ('CORE_STBL', models.IntegerField(max_length=4)),
                ('BP_STBL', models.IntegerField(max_length=4)),
                ('COMFORT', models.IntegerField(max_length=4)),
                ('DESCISION', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='registration_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('pub_date', models.DateField(default=datetime.datetime(2020, 3, 18, 11, 36, 29, 393443, tzinfo=utc))),
            ],
        ),
        migrations.DeleteModel(
            name='registrationdata',
        ),
    ]
